repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.0,flake8-quotes==3.2.0]

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
    -   id: gitlint

-   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
    -   id: dockerfile_lint
